baseURL = "https://www.public.asu.edu/~saghafoo/"
languageCode = "en-us"
title = "Suhail Ghafoor | Manager Information technology @ ASU"
theme = "strapped"
staticDir = ["static"]

[params]
    description =   """Manager Information Technology @ ASU, Consultant @ Pathfinder Center, Biodesign institute. I know how to use a paper shredder."""
    author = "Suhail Ghafoor"