baseURL = "http://www.public.asu.edu/~saghafoo/"
languageCode = "en-us"
title = "Suhail Ghafoor | Manager Information technology @ ASU"
theme = "strapped"
staticDir = ["static"]

[params]
    description =   "Currently working as a web developer at ASU while studying computer science and graduating in Spring 2019. I know how to use a paper shredder."
    author = "Suhail Ghafoor"